### ISSUE TITLE
TypeError when uploading a picture

### ISSUE THREAD

**Issue by kinoute** [twitter/twurl#109]
Hi,

I don't know if this gem is compatible with ruby 2.6.0, but I'm getting an error every time I try to use the  `media/upload.json` endpoint to upload a picture or a gif.

I tried the statuses/update endpoint and it works so It's not an authentification error.

### Expected behavior

Get the media_id of the upload.

### Actual behavior

```
 twurl -X POST -H upload.twitter.com "/1.1/media/upload.json" -f test.png
Traceback (most recent call last):
	28: from /Users/kinoute/.rvm/gems/ruby-2.6.0/bin/ruby_executable_hooks:24:in `<main>'
	27: from /Users/kinoute/.rvm/gems/ruby-2.6.0/bin/ruby_executable_hooks:24:in `eval'
	26: from /Users/kinoute/.rvm/gems/ruby-2.6.0/bin/twurl:23:in `<main>'
	25: from /Users/kinoute/.rvm/gems/ruby-2.6.0/bin/twurl:23:in `load'
	24: from /Users/kinoute/.rvm/gems/ruby-2.6.0/gems/twurl-0.9.3/bin/twurl:4:in `<top (required)>'
	23: from /Users/kinoute/.rvm/gems/ruby-2.6.0/gems/twurl-0.9.3/lib/twurl/cli.rb:21:in `run'
	22: from /Users/kinoute/.rvm/gems/ruby-2.6.0/gems/twurl-0.9.3/lib/twurl/cli.rb:38:in `dispatch'
	21: from /Users/kinoute/.rvm/gems/ruby-2.6.0/gems/twurl-0.9.3/lib/twurl/abstract_command_controller.rb:7:in `dispatch'
	20: from /Users/kinoute/.rvm/gems/ruby-2.6.0/gems/twurl-0.9.3/lib/twurl/request_controller.rb:9:in `dispatch'
	19: from /Users/kinoute/.rvm/gems/ruby-2.6.0/gems/twurl-0.9.3/lib/twurl/request_controller.rb:13:in `perform_request'
	18: from /Users/kinoute/.rvm/gems/ruby-2.6.0/gems/twurl-0.9.3/lib/twurl/oauth_client.rb:118:in `perform_request_from_options'
	17: from /Users/kinoute/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/net/http.rb:1470:in `request'
	16: from /Users/kinoute/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/net/http.rb:920:in `start'
	15: from /Users/kinoute/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/net/http.rb:1472:in `block in request'
	14: from /Users/kinoute/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/net/http.rb:1479:in `request'
	13: from /Users/kinoute/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/net/http.rb:1506:in `transport_request'
	12: from /Users/kinoute/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/net/http.rb:1506:in `catch'
	11: from /Users/kinoute/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/net/http.rb:1507:in `block in transport_request'
	10: from /Users/kinoute/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/net/http/generic_request.rb:123:in `exec'
	 9: from /Users/kinoute/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/net/http/generic_request.rb:189:in `send_request_with_body'
	 8: from /Users/kinoute/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/net/protocol.rb:247:in `write'
	 7: from /Users/kinoute/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/net/protocol.rb:265:in `writing'
	 6: from /Users/kinoute/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/net/protocol.rb:248:in `block in write'
	 5: from /Users/kinoute/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/net/protocol.rb:275:in `write0'
	 4: from /Users/kinoute/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/net/protocol.rb:275:in `each_with_index'
	 3: from /Users/kinoute/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/net/protocol.rb:275:in `each'
	 2: from /Users/kinoute/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/net/protocol.rb:277:in `block in write0'
	 1: from /Users/kinoute/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/openssl/buffering.rb:383:in `write_nonblock'
/Users/kinoute/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/openssl/buffering.rb:383:in `syswrite_nonblock': no implicit conversion of nil into String (TypeError)
```

When using the `-t` argument, I can see that the upload starts, but then the connection is closed due to:

`Conn close because of error no implicit conversion of nil into String`

### Steps to reproduce the behavior

- Install ruby 2.6.0
- Install the twurl gem
- Download this picture https://reho.st/self/efdaab291705365856bbb0c1bff4442f6d17b5c9.png
- Do  `twurl -X POST -H upload.twitter.com "/1.1/media/upload.json" -f test.png`

**Comment by smaeda-ks** [comment]
Hi @kinoute ,

Could you try this?
https://github.com/twitter/twurl/issues/89#issuecomment-454977428

**Comment by kinoute** [comment]
hi @smaeda-ks,

Your fix works!

**Comment by smaeda-ks** [comment]
@kinoute That's good news. I opened a PR for this as you can see https://github.com/twitter/twurl/pull/110 , so you may want to close this issue so far.

**Comment by kinoute** [comment]
Sure. Done
