### ISSUE TITLE
twurl -d "status=Tweet from twurl" /1/statuses/update.xml breaks 

### ISSUE THREAD

**Issue by nacho4d** [twitter/twurl#21]
I did `sudo gem install twurl` and everything when fine and version 0.6.7 is successfully installed :)
Then authorized the app `twurl authorize -u X -p X --consumer-key X --consumer-secret X` and supplied the pin and got : `Authorization successful` Yay!

Sadly 

```
twurl -d "status=Tweet from twurl" /1/statuses/update.xml
```

leads to

```
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/yaml.rb:133:in `load': syntax error on line 14, col -1: `' (ArgumentError)
from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/yaml.rb:133:in `load'
from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/yaml.rb:144:in `load_file'
from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/yaml.rb:143:in `open'
from /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/yaml.rb:143:in `load_file'
from /Library/Ruby/Gems/1.8/gems/twurl-0.6.7/bin/../lib/twurl/rcfile.rb:18:in `load'
from /Library/Ruby/Gems/1.8/gems/twurl-0.6.7/bin/../lib/twurl/rcfile.rb:30:in `initialize'
from /Library/Ruby/Gems/1.8/gems/twurl-0.6.7/bin/../lib/twurl/oauth_client.rb:6:in `new'
from /Library/Ruby/Gems/1.8/gems/twurl-0.6.7/bin/../lib/twurl/oauth_client.rb:6:in `rcfile'
from /Library/Ruby/Gems/1.8/gems/twurl-0.6.7/bin/../lib/twurl/oauth_client.rb:12:in `load_from_options'
from /Library/Ruby/Gems/1.8/gems/twurl-0.6.7/bin/../lib/twurl/cli.rb:18:in `dispatch'
from /Library/Ruby/Gems/1.8/gems/twurl-0.6.7/bin/../lib/twurl/cli.rb:14:in `run'
from /Library/Ruby/Gems/1.8/gems/twurl-0.6.7/bin/twurl:4
from /usr/bin/twurl:19:in `load'
from /usr/bin/twurl:19
```

Have tried other commands like `twurl /1/statuses/home_timeline.xml` and it works flawless ... I have 0 ruby knowledge so I can't help ;(

**Comment by andypiper** [comment]
Closing for age / inability to repro - please open a new issue if this still occurs with 0.9.3 (NB xml endpoints are no more)
