### ISSUE TITLE
Unable to Enter Authorization PIN

### ISSUE THREAD

**Issue by hawt** [twitter/twurl#57]
##### I receive the following output in my terminal and am unable to enter my Authorization PIN. 

```terminal
/usr/local/var/rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/twurl-0.9.2/lib/twurl/oauth_client.rb:136:in `gets': Is a directory @ io_fillbuf - fd:9 / (Errno::EISDIR)
	from /usr/local/var/rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/twurl-0.9.2/lib/twurl/oauth_client.rb:136:in `gets'
	from /usr/local/var/rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/twurl-0.9.2/lib/twurl/oauth_client.rb:136:in `perform_pin_authorize_workflow'
	from /usr/local/var/rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/twurl-0.9.2/lib/twurl/oauth_client.rb:123:in `rescue in exchange_credentials_for_access_token'
	from /usr/local/var/rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/twurl-0.9.2/lib/twurl/oauth_client.rb:120:in `exchange_credentials_for_access_token'
	from /usr/local/var/rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/twurl-0.9.2/lib/twurl/authorization_controller.rb:6:in `dispatch'
	from /usr/local/var/rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/twurl-0.9.2/lib/twurl/abstract_command_controller.rb:7:in `dispatch'
	from /usr/local/var/rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/twurl-0.9.2/lib/twurl/cli.rb:38:in `dispatch'
	from /usr/local/var/rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/twurl-0.9.2/lib/twurl/cli.rb:21:in `run'
	from /usr/local/var/rbenv/versions/2.1.4/lib/ruby/gems/2.1.0/gems/twurl-0.9.2/bin/twurl:4:in `<top (required)>'
	from /usr/local/var/rbenv/versions/2.1.4/bin/twurl:23:in `load'
	from /usr/local/var/rbenv/versions/2.1.4/bin/twurl:23:in `<main>'
```

I am running Ruby Version: 
*ruby 2.1.4p265 (2014-10-27 revision 48166) [x86_64-darwin14.0]*

How do I fix this so I can get the PIN prompt inside terminal?

**Comment by fmborghino** [comment]
This is a long-shot, but are you redirecting input to twurl from a path that is a directory? I can repro your stack by doing this:

twurl authorize --consumer-key my_new_key --consumer-secret my_new_secret < /tmp

I guess this comes down to making sure you are entering only this into your terminal:

twurl authorize --consumer-key my_new_key --consumer-secret my_new_secret

**Comment by hawt** [comment]
Thank you for responding @fmborghino. I believe you have helped me pinpoint the problem. 

##### How I Solved The Problem
When I ran the command I included the "/" character between my_new_key and --consumer-secret

##### The README had the "/". (The confusion)

```
% twurl authorize --consumer-key key       \
                    --consumer-secret secret
```

I have this working now.
