### ISSUE TITLE
`twurl accounts` throws errors

### ISSUE THREAD

**Issue by meyerweb** [twitter/twurl#76]
I was unable to use `accounts`, so I ran `gem uninstall twurl` and then `gem install twurl`, getting 0.9.3.  I made sure all my other gems were updated.  I authorized my Twitter account, and can post to it from the command line.  But when I type `twurl accounts`, I still get the following:

```
/Users/emeyer/.rvm/gems/ruby-2.1.1/gems/twurl-0.9.3/lib/twurl/account_information_controller.rb:11:in `sort': comparison of NilClass with String failed (ArgumentError)
	from /Users/emeyer/.rvm/gems/ruby-2.1.1/gems/twurl-0.9.3/lib/twurl/account_information_controller.rb:11:in `dispatch'
	from /Users/emeyer/.rvm/gems/ruby-2.1.1/gems/twurl-0.9.3/lib/twurl/abstract_command_controller.rb:7:in `dispatch'
	from /Users/emeyer/.rvm/gems/ruby-2.1.1/gems/twurl-0.9.3/lib/twurl/cli.rb:38:in `dispatch'
	from /Users/emeyer/.rvm/gems/ruby-2.1.1/gems/twurl-0.9.3/lib/twurl/cli.rb:21:in `run'
	from /Users/emeyer/.rvm/gems/ruby-2.1.1/gems/twurl-0.9.3/bin/twurl:4:in `<top (required)>'
	from /Users/emeyer/.rvm/gems/ruby-2.1.1/bin/twurl:23:in `load'
	from /Users/emeyer/.rvm/gems/ruby-2.1.1/bin/twurl:23:in `<main>'
	from /Users/emeyer/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/emeyer/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by andypiper** [comment]
Is your `.twurlrc` file valid? Can you try deleting that, re-authenticating twurl, and running again?

**Comment by meyerweb** [comment]
That seems to have fixed it.  Thanks!
